/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2017-08-25 06:39:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.monitor;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class zooKeeperRegisterPAGE_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/common/taglibs.jsp", Long.valueOf(1329715404000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".mytable {align:center;border-collapse:collapse;border:solid #6AA70B;border-width:0px 0 0 0px;width:600;} \r\n");
      out.write(".mytable table tr {list-style:none; border-bottom:#6AA70B 1px dotted ;font-size: 12px;;height:20px;} \r\n");
      out.write(".mytable table tr.t1 {background-color:#EEEEEE;}/* 第一行的背景色 */ \r\n");
      out.write(".mytable table tr.t2{background-color:#;}/* 第二行的背景色 */ \r\n");
      out.write(".mytable table tr.t3 {background-color:#CCCCCC;}/* 鼠标经过时的背景色 */ \r\n");
      out.write("</style> \r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("a:link { text-decoration: none}\r\n");
      out.write("a:active { text-decoration:none}\r\n");
      out.write("a:hover { text-decoration:none} \r\n");
      out.write("a:visited { text-decoration:none}\r\n");
      out.write("</style>\r\n");
      out.write("<h1>ZooKeeper 注册</h1>\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\" class=\"mytable\" id=\"tab\">\r\n");
      out.write("\r\n");
      out.write("<form name=\"registerZooKeeper\"  id=\"registerZooKeeper\"  action=\"zooKeeper.do?method=registerZooKeeperHandle\"  method=\"post\">\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t <tr style=\"background-color:#D3D1D1; text-align:center;\">\r\n");
      out.write("\t\t \t<td><b>配置项</b></td>\r\n");
      out.write("\t\t \t<td><b>设置参数</b></td>\r\n");
      out.write("\t\t </tr>\r\n");
      out.write("\t\t <tr>\r\n");
      out.write("\t\t \t<td valign=\"middle\">ZooKeeper集群名称</td>\r\n");
      out.write("\t\t \t<td valign=\"middle\" ><input type=\"text\" name=\"clusterName\" id=\"clusterName\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${zooKeeperCluster.clusterName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" size=\"100\"/></td>\r\n");
      out.write("\t\t </tr>\r\n");
      out.write("\t\t <tr >\r\n");
      out.write("\t\t \t<td valign=\"middle\">机器列表</td>\r\n");
      out.write("\t\t \t<td valign=\"middle\" ><input type=\"text\" name=\"serverListString\"  id=\"serverListString\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${zooKeeperClusterServerList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" size=\"100\"/></td>\r\n");
      out.write("\t\t </tr>\r\n");
      out.write("\t\t <tr >\r\n");
      out.write("\t\t \t<td valign=\"middle\">描述</td>\r\n");
      out.write("\t\t \t<td valign=\"middle\" ><input type=\"text\" name=\"description\" id=\"description\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${zooKeeperCluster.description}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" size=\"100\"/></td>\r\n");
      out.write("\t\t </tr>\r\n");
      out.write("\t\t <tr >\r\n");
      out.write("\t\t \t<td valign=\"middle\"></td>\r\n");
      out.write("\t\t \t<td align=\"right\" ><input type=\"submit\"  value=\"Register Now\"  size=\"90\"/> <font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${handleMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font> </td>\r\n");
      out.write("\t\t </tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("\r\n");
      out.write("var Ptr=document.getElementById(\"tab\").getElementsByTagName(\"tr\"); \r\n");
      out.write("function $() { \r\n");
      out.write("for (i=1;i<Ptr.length+1;i++) { \r\n");
      out.write("Ptr[i-1].className = (i%2>0)?\"t1\":\"t2\"; \r\n");
      out.write("} \r\n");
      out.write("} \r\n");
      out.write("window.onload=$; \r\n");
      out.write("for(var i=0;i<Ptr.length;i++) { \r\n");
      out.write("Ptr[i].onmouseover=function(){ \r\n");
      out.write("this.tmpClass=this.className; \r\n");
      out.write("this.className = \"t3\"; \r\n");
      out.write("}; \r\n");
      out.write("Ptr[i].onmouseout=function(){ \r\n");
      out.write("this.className=this.tmpClass; \r\n");
      out.write("}; \r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
