/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2017-08-25 06:39:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class switchOfNeedAlarmPAGE_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/common/taglibs.jsp", Long.valueOf(1329715404000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=GBK");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".mytable {align:center;border-collapse:collapse;border:solid #6AA70B;border-width:0px 0 0 0px;width:600;} \r\n");
      out.write(".mytable table tr {padding-top:5px;list-style:none; border-bottom:#6AA70B 1px dotted ;font-size: 12px;;height:20px;} \r\n");
      out.write(".mytable table tr.t1 {background-color:#EEEEEE;}/* 第一行的背景色 */ \r\n");
      out.write(".mytable table tr.t2{background-color:#;}/* 第二行的背景色 */ \r\n");
      out.write(".mytable table tr.t3 {background-color:#CCCCCC;}/* 鼠标经过时的背景色 */ \r\n");
      out.write("</style> \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/popDiv.css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("a:link { text-decoration: none}\r\n");
      out.write("a:active { text-decoration:none}\r\n");
      out.write("a:hover { text-decoration:none} \r\n");
      out.write("a:visited { text-decoration:none}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1>管理员-ZooKeeper 监控报警开关</h1>\r\n");
      out.write("<div align=\"center\" class=\"mytable\" id=\"tab\">\r\n");
      out.write("<form name=\"updateSwitchOfAlarm\"  id=\"updateSwitchOfAlarm\"  action=\"admin.do?method=updateSwitchOfNeedAlarmHandle\"  method=\"post\">\r\n");
      out.write("\t<table border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("\t\t<tr style=\"background-color:#DDDDDE; text-align:center;\">\r\n");
      out.write("\t\t\t<td><b>监控报警开关</b></td>\r\n");
      out.write("\t\t\t<td></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td align=\"right\" ><input type=\"submit\"  value=\"Update\"  size=\"90\"/> <font color=\"red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${handleMessage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</font> </td>\r\n");
      out.write("\t\t</tr>\t\t\t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("var Ptr=document.getElementById(\"tab\").getElementsByTagName(\"tr\"); \r\n");
      out.write("function $() { \r\n");
      out.write("for (i=1;i<Ptr.length+1;i++) { \r\n");
      out.write("Ptr[i-1].className = (i%2>0)?\"t1\":\"t2\"; \r\n");
      out.write("} \r\n");
      out.write("} \r\n");
      out.write("window.onload=$; \r\n");
      out.write("for(var i=0;i<Ptr.length;i++) { \r\n");
      out.write("Ptr[i].onmouseover=function(){ \r\n");
      out.write("this.tmpClass=this.className; \r\n");
      out.write("this.className = \"t3\"; \r\n");
      out.write("}; \r\n");
      out.write("Ptr[i].onmouseout=function(){ \r\n");
      out.write("this.className=this.tmpClass; \r\n");
      out.write("}; \r\n");
      out.write("} \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<SCRIPT type=text/javascript>\r\n");
      out.write("function NeatDialog(sHTML, sTitle, bCancel)\r\n");
      out.write("{\r\n");
      out.write("  window.neatDialog = null;\r\n");
      out.write("  this.elt = null;\r\n");
      out.write("  if (document.createElement  &&  document.getElementById)\r\n");
      out.write("  {\r\n");
      out.write("    var dg = document.createElement(\"div\");\r\n");
      out.write("    dg.className = \"neat-dialog\";\r\n");
      out.write("    if (sTitle)\r\n");
      out.write("      sHTML = '<div class=\"neat-dialog-title\">'+sTitle+\r\n");
      out.write("              ((bCancel)?\r\n");
      out.write("                '<img src=\"x.gif\" alt=\"Cancel\" class=\"nd-cancel\" />':'')+\r\n");
      out.write("                '</div>\\n' + sHTML;\r\n");
      out.write("    dg.innerHTML = sHTML;\r\n");
      out.write("    var dbg = document.createElement(\"div\");\r\n");
      out.write("    dbg.id = \"nd-bdg\";\r\n");
      out.write("    dbg.className = \"neat-dialog-bg\";\r\n");
      out.write("    var dgc = document.createElement(\"div\");\r\n");
      out.write("    dgc.className = \"neat-dialog-cont\";\r\n");
      out.write("    dgc.appendChild(dbg);\r\n");
      out.write("    dgc.appendChild(dg);\r\n");
      out.write("    if (document.body.offsetLeft > 0)\r\n");
      out.write("    dgc.style.marginLeft = document.body.offsetLeft + \"px\";\r\n");
      out.write("    document.body.appendChild(dgc);\r\n");
      out.write("    if (bCancel) document.getElementById(\"nd-cancel\").onclick = function()\r\n");
      out.write("    {\r\n");
      out.write("      window.neatDialog.close();\r\n");
      out.write("    };\r\n");
      out.write("    this.elt = dgc;\r\n");
      out.write("    window.neatDialog = this;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("NeatDialog.prototype.close = function()\r\n");
      out.write("{\r\n");
      out.write("  if (this.elt)\r\n");
      out.write("  {\r\n");
      out.write("    this.elt.style.display = \"none\";\r\n");
      out.write("    this.elt.parentNode.removeChild(this.elt);\r\n");
      out.write("  }\r\n");
      out.write("  window.neatDialog = null;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openDialog( content )\r\n");
      out.write("  {\r\n");
      out.write("var sHTML = content+\r\n");
      out.write("      '<p><button onclick=\"window.neatDialog.close()\">关闭</button></p>';\r\n");
      out.write("    new NeatDialog(sHTML, \"<b>节点详情</b>\", false);\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("</SCRIPT>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/jsp/admin/switchOfNeedAlarmPAGE.jsp(33,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ needAlarm eq 'true' }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<input type=\"radio\" name=\"needAlarm\" value = \"true\" checked=\"checked\">开启 <input type=\"radio\" name=\"needAlarm\" value = \"false\"  >关闭");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/jsp/admin/switchOfNeedAlarmPAGE.jsp(34,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ needAlarm eq 'false' }", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
    if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<input type=\"radio\" name=\"needAlarm\" value = \"true\" >开启 <input type=\"radio\" name=\"needAlarm\" value = \"false\"  checked=\"checked\">关闭");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
    return false;
  }
}
